POST http://localhost:8002/auth/signup
Content-Type: application/json

{
    "firstName": "Mary",
    "lastName": "Jane",
    "email": "maryjane@gmail.com",
    "password": "1234abcd&"
}

###

POST http://localhost:8002/auth/login
Content-Type: application/json

{
    "email": "maryjane@gmail.com",
    "password": "1234abcd&"
}

###

POST http://localhost:8002/auth/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQwNTE3MzViOWQwMWEwZWRhMDY3MGI5IiwiaWF0IjoxNjc4MTk0NzMzfQ.OH7k2eci_FZ3VhhtNqLcx5ILWC3tkreq75J19HL44oA"
}

###

DELETE http://localhost:8002/auth/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjQwNTE3MzViOWQwMWEwZWRhMDY3MGI5IiwiaWF0IjoxNjc4MTk0NzMzfQ.OH7k2eci_FZ3VhhtNqLcx5ILWC3tkreq75J19HL44oA"
}
